
runtime: php72 # or another supported version

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
- url: /(.+\.(gif|png|jpg|css|js|map|PNG))$
  static_dir: \1
  upload: .+\.(gif|png|jpg|css|js|map|PNG))$

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

  entrypoint:
  server handler.php

  env_variavbles:

  CLOUDSQL_USER: root
  CLOUDSQL_DB: flms
  CLOUDSQL_PASSWORD: NUSUM123
  CLOUDSQL_DSN: /cloudsql/phpapp-